# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
    jobs:
    build:
    docker:
      - image: circleci/openjdk:11.0.1-jdk
    steps:
      - checkout
      - run: mvn clean package
      - run: mvn clean compile jib:build
    -Djib.to.auth.username=$DOCKER_USER
    -Djib.to.auth.password=$DOCKER_PASS
    -Dimage=khanimhuseynzada/circlecitest:$CIRCLE_BUILD_NUM